CSV_FILE_PATH = "C://Data/Incidents_2016_2017_archiviert.csv"
CSV_FILE_ENCODING = "utf-8"
CSV_FILE_SEPARATOR = ";"
PANDAS_INDEX_NAME = "FullId"
ATTRIBUTE_SETTINGS_LOCATION = "./settings/attributes"
REPORT_DIRECTORY = "C://Data/Reports"
